language: python

matrix:
    include:
        - os: linux
          python: 2.7
        - os: linux
          python: 3.6
before_install: |
  if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
  fi  
  export TRAVIS_PYTHON_PATH=`which python`
install:
  - yarn
  # - code --install-extension ms-python.python

script:
  - yarn run compile
  - yarn run testSingleWorkspace --silent
  - yarn run testMultiWorkspace --silent
